"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { BarChart3, ChevronDown, Eye, FolderKanban, Gauge, Menu, Plus, Settings, Sparkles, User } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { ThemeToggle } from "@/components/ui/theme-toggle";
import { DashboardMotion } from "@/features/dashboard/components/dashboard-motion";
import { cn } from "@/lib/utils";
const nav = [{ href: "/dashboard", label: "Tổng quan", icon: Gauge }, { href: "/dashboard/new", label: "New Audit", icon: Plus }, { href: "/dashboard/projects", label: "Dự án", icon: FolderKanban }, { href: "/dashboard/usage", label: "Sử dụng", icon: BarChart3 }];
export function DashboardShell({ children, email, demo }: { children: React.ReactNode; email: string; demo: boolean }) {
  const pathname = usePathname(); const [mobileOpen, setMobileOpen] = useState(false);
  return <div className="min-h-screen bg-muted/20"><header className="sticky top-0 z-40 border-b bg-background/90 backdrop-blur-xl"><div className="flex h-16 items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3"><Button variant="ghost" size="sm" className="md:hidden" aria-label="Mở điều hướng" onClick={()=>setMobileOpen(v=>!v)}><Menu className="size-5"/></Button><Link href="/dashboard" className="flex items-center gap-2 font-bold"><Eye className="text-primary"/>UXLens AI</Link>{demo&&<span className="hidden rounded-full bg-amber-500/10 px-2 py-0.5 text-[10px] font-semibold text-amber-600 sm:inline">DEMO MODE</span>}</div><div className="flex items-center gap-2"><ThemeToggle/><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="gap-2"><span className="grid size-7 place-items-center rounded-full bg-primary/10"><User className="size-3.5 text-primary"/></span><span className="hidden max-w-40 truncate text-sm sm:block">{email}</span><ChevronDown className="size-3.5 text-muted-foreground"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem><User className="mr-2 size-4"/>Tài khoản</DropdownMenuItem><DropdownMenuItem><Settings className="mr-2 size-4"/>Cài đặt</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem>Đăng xuất</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div></header>{mobileOpen&&<div className="fixed inset-x-0 top-16 z-30 border-b bg-background p-3 shadow-lg md:hidden"><nav className="grid grid-cols-2 gap-2">{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} onClick={()=>setMobileOpen(false)} className="flex items-center gap-2 rounded-md border p-3 text-sm"><Icon className="size-4 text-primary"/>{label}</Link>)}</nav></div>}<div className="mx-auto grid max-w-[1440px] md:grid-cols-[232px_1fr]"><aside className="sticky top-16 hidden h-[calc(100vh-4rem)] border-r p-4 md:flex md:flex-col"><nav className="space-y-1">{nav.map(({href,label,icon:Icon})=>{const active=href==="/dashboard"?pathname===href:pathname.startsWith(href);return <Link key={href} href={href} className={cn("group flex items-center gap-3 rounded-md px-3 py-2 text-sm transition",active?"bg-primary/10 font-medium text-primary":"text-muted-foreground hover:translate-x-1 hover:bg-accent hover:text-foreground")}><Icon className="size-4 transition-transform group-hover:scale-110"/>{label}</Link>})}</nav><div data-upgrade-card className="mt-auto rounded-lg border bg-card p-4 transition hover:-translate-y-1 hover:border-primary/40 hover:shadow-lg hover:shadow-primary/10"><Sparkles className="size-5 animate-pulse text-primary"/><p className="mt-3 text-sm font-semibold">Mở khóa Pro</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Audit không giới hạn và export báo cáo.</p><Button size="sm" className="mt-3 w-full">Nâng cấp $9</Button></div></aside><main className="min-w-0 p-4 sm:p-6 lg:p-8"><DashboardMotion>{children}</DashboardMotion></main></div></div>;
}