import Link from "next/link";
import { Check,Sparkles } from "lucide-react";
import { FunnelEvent } from "@/components/funnel-event";
import { BillingButton } from "@/components/billing-button";
import { BrandLogo } from "@/components/brand-logo";
import { Button } from "@/components/ui/button";
import { isBillingConfigured } from "@/lib/stripe";
const free=["3 audits mỗi tháng","5 tiêu chí UX","Lịch sử và Projects","Private screenshots"];
const pro=["Audit không giới hạn","Full structured AI report","Public/private share links","Billing Portal và ưu tiên tính năng"];
export default function PricingPage(){const disabledReason=isBillingConfigured()?undefined:"Demo Mode: cần cấu hình Supabase và Stripe để mở checkout.";return <><FunnelEvent name="pricing_view"/><main className="min-h-screen bg-background"><header className="border-b"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><Link href="/vi" aria-label="UXLens AI"><BrandLogo compact/></Link><Button asChild variant="ghost"><Link href="/dashboard">Dashboard</Link></Button></div></header><section className="mx-auto max-w-5xl px-5 py-20 text-center"><span className="rounded-full bg-primary/10 px-3 py-1 text-sm font-medium text-primary">Pricing đơn giản</span><h1 className="mt-6 text-4xl font-bold sm:text-6xl">Bắt đầu miễn phí.<br/>Nâng cấp khi cần.</h1><p className="mx-auto mt-5 max-w-xl text-muted-foreground">Không thu phí theo screenshot. Không cấp Pro từ redirect — quyền truy cập chỉ được xác nhận bởi Stripe webhook.</p><div className="mt-12 grid gap-6 text-left md:grid-cols-2"><article className="rounded-lg border bg-card p-7"><p className="font-semibold">FREE</p><p className="mt-4 text-4xl font-bold">$0</p><p className="text-sm text-muted-foreground">mãi mãi</p><ul className="mt-7 space-y-3">{free.map(x=><li key={x} className="flex gap-2 text-sm"><Check className="size-4 text-primary"/>{x}</li>)}</ul><Button asChild variant="outline" className="mt-8 w-full"><Link href="/dashboard/new">Tạo audit miễn phí</Link></Button></article><article className="relative overflow-hidden rounded-lg border border-primary/40 bg-card p-7 shadow-xl shadow-primary/10"><Sparkles className="absolute right-6 top-6 text-primary"/><p className="font-semibold text-primary">PRO</p><p className="mt-4 text-4xl font-bold">$9</p><p className="text-sm text-muted-foreground">mỗi tháng</p><ul className="mt-7 space-y-3">{pro.map(x=><li key={x} className="flex gap-2 text-sm"><Check className="size-4 text-primary"/>{x}</li>)}</ul><BillingButton disabledReason={disabledReason} className="mt-8 w-full">Upgrade Pro</BillingButton></article></div></section></main></>}
