"use server";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
const emailSchema=z.string().trim().email("Email không hợp lệ");const passwordSchema=z.string().min(8,"Mật khẩu cần ít nhất 8 ký tự");
function configured(){return Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)}
function go(path:string,key:"error"|"message",value:string):never{redirect(`${path}?${key}=${encodeURIComponent(value)}`)}
export async function signIn(form:FormData){const parsed=z.object({email:emailSchema,password:passwordSchema}).safeParse({email:form.get("email"),password:form.get("password")});if(!parsed.success)go("/login","error",parsed.error.issues[0].message);if(!configured()){const store=await cookies();store.set("uxlens_demo_session",parsed.data.email,{httpOnly:true,sameSite:"lax",path:"/",maxAge:604800});redirect("/dashboard")}const supabase=await createClient();const{error}=await supabase.auth.signInWithPassword(parsed.data);if(error)go("/login","error",error.message);redirect("/dashboard")}
export async function signUp(form:FormData){const parsed=z.object({fullName:z.string().trim().min(2,"Tên cần ít nhất 2 ký tự"),email:emailSchema,password:passwordSchema,confirm:z.string()}).refine(x=>x.password===x.confirm,{message:"Mật khẩu xác nhận không khớp",path:["confirm"]}).safeParse({fullName:form.get("fullName"),email:form.get("email"),password:form.get("password"),confirm:form.get("confirm")});if(!parsed.success)go("/register","error",parsed.error.issues[0].message);if(!configured()){const store=await cookies();store.set("uxlens_demo_session",parsed.data.email,{httpOnly:true,sameSite:"lax",path:"/",maxAge:604800});redirect("/dashboard?signup=success")}const supabase=await createClient();const origin=process.env.NEXT_PUBLIC_APP_URL??"http://localhost:3000";const{data,error}=await supabase.auth.signUp({email:parsed.data.email,password:parsed.data.password,options:{data:{full_name:parsed.data.fullName},emailRedirectTo:`${origin}/auth/callback?next=/dashboard`}});if(error)go("/register","error",error.message);if(data.session)redirect("/dashboard?signup=success");go("/login","message","Đăng ký thành công. Hãy kiểm tra email để xác nhận tài khoản.")}
export async function forgotPassword(form:FormData){if(!configured())go("/forgot-password","message","Demo Mode không gửi email. Hãy cấu hình Supabase để dùng reset password.");const parsed=emailSchema.safeParse(form.get("email"));if(!parsed.success)go("/forgot-password","error",parsed.error.issues[0].message);const supabase=await createClient();const origin=process.env.NEXT_PUBLIC_APP_URL??"http://localhost:3000";const{error}=await supabase.auth.resetPasswordForEmail(parsed.data,{redirectTo:`${origin}/auth/callback?next=/reset-password`});if(error)go("/forgot-password","error",error.message);go("/forgot-password","message","Đã gửi liên kết đặt lại mật khẩu. Hãy kiểm tra email.")}
export async function resetPassword(form:FormData){const parsed=z.object({password:passwordSchema,confirm:z.string()}).refine(x=>x.password===x.confirm,{message:"Mật khẩu xác nhận không khớp",path:["confirm"]}).safeParse({password:form.get("password"),confirm:form.get("confirm")});if(!parsed.success)go("/reset-password","error",parsed.error.issues[0].message);if(!configured())go("/login","message","Demo Mode: mật khẩu không được lưu.");const supabase=await createClient();const{error}=await supabase.auth.updateUser({password:parsed.data.password});if(error)go("/reset-password","error",error.message);go("/login","message","Mật khẩu đã được cập nhật.")}
export async function signOut(){if(configured()){const supabase=await createClient();await supabase.auth.signOut()}else{const store=await cookies();store.delete("uxlens_demo_session")}redirect("/vi")}
