import type { Locale } from "./config";
const vi = {
  nav: { features: "Tính năng", how: "Cách hoạt động", pricing: "Bảng giá", faq: "FAQ", login: "Đăng nhập" },
  hero: { badge: "AI-powered UX audit", title: "Biến screenshot thành quyết định UX rõ ràng.", description: "Phát hiện vấn đề usability và accessibility trong vài giây. Nhận đề xuất cụ thể để thiết kế tốt hơn trước khi ship.", primary: "Audit miễn phí", secondary: "Xem sản phẩm", note: "Không cần thẻ tín dụng · Có kết quả trong vài giây" },
  preview: { file: "Screenshot đã tải lên", issue: "CTA thiếu tương phản", recommendation: "Tăng contrast ratio để cải thiện khả năng đọc." },
  proof: "Được xây dựng cho những team ship sản phẩm nhanh",
  features: { badge: "Tính năng", title: "Một UX reviewer luôn sẵn sàng.", description: "Từ screenshot đến danh sách cải tiến có thể đưa thẳng vào backlog.", items: [["Audit có cấu trúc","Chấm điểm usability, accessibility, hierarchy, consistency và UX writing."],["AI hiểu ngữ cảnh","Phân tích dựa trên mục tiêu sản phẩm thay vì phản hồi thiết kế chung chung."],["Ưu tiên rõ ràng","Critical, high, medium, low giúp team biết vấn đề nào cần sửa trước."],["Accessibility","Phát hiện contrast, readability, target size và các rào cản phổ biến."],["Theo dõi tiến bộ","Lưu lịch sử audit theo dự án và so sánh chất lượng qua từng phiên bản."],["Riêng tư mặc định","Screenshot được lưu trong private bucket với Row Level Security."]] },
  how: { badge: "Cách hoạt động", title: "Từ ảnh đến insight trong 3 bước.", items: [["Tải screenshot","PNG, JPG hoặc WebP từ bất kỳ màn hình nào."],["AI phân tích","Vision model đánh giá theo 5 nhóm tiêu chí UX."],["Nhận báo cáo","Xem điểm số, vấn đề và đề xuất được ưu tiên."]] },
  cases: { badge: "Use cases", title: "Hữu ích ở mọi bước thiết kế.", items: [["Designer","Có thêm góc nhìn trước design review và handoff."],["Product team","Đánh giá flow nhanh trước khi đưa vào sprint."],["Agency","Chuẩn hóa chất lượng audit giữa nhiều dự án khách hàng."],["Founder","Tự kiểm tra MVP khi chưa có UX specialist toàn thời gian."]] },
  comparison: { badge: "Trước / Sau", title: "Bớt phỏng đoán. Thêm bằng chứng.", before: "Trước UXLens", after: "Sau UXLens", beforeItems: ["Feedback cảm tính và rời rạc","Không rõ vấn đề nào quan trọng nhất","Mất nhiều giờ chuẩn bị design review","Lỗi accessibility dễ bị bỏ qua"], afterItems: ["Điểm số nhất quán theo 5 tiêu chí","Issues xếp theo mức độ ảnh hưởng","Đề xuất cụ thể, có thể hành động","Lưu lịch sử để theo dõi tiến bộ"] },
  pricing: { badge: "Bảng giá", title: "Bắt đầu miễn phí, nâng cấp khi cần.", description: "Giá đơn giản, không phí ẩn.", month: "/ tháng", popular: "Phổ biến", freeCta: "Bắt đầu miễn phí", proCta: "Dùng thử Pro", free: ["3 audit mỗi tháng","5 nhóm điểm UX","Issue được ưu tiên","Lưu lịch sử 30 ngày"], pro: ["Audit không giới hạn","Phân tích AI chi tiết","Lịch sử không giới hạn","Export báo cáo","Ưu tiên xử lý"] },
  faq: { badge: "FAQ", title: "Câu hỏi thường gặp.", items: [["UXLens thay thế UX researcher không?","Không. UXLens giúp phát hiện nhanh vấn đề heuristic để team chuẩn bị tốt hơn cho nghiên cứu và review chuyên sâu."],["Screenshot của tôi có an toàn không?","Ảnh nằm trong private Supabase Storage bucket, được bảo vệ bằng Row Level Security theo tài khoản."],["AI đánh giá những tiêu chí nào?","Usability, accessibility, visual hierarchy, consistency và UX writing."],["Tôi có thể hủy Pro bất kỳ lúc nào không?","Có. Bạn có thể hủy và tiếp tục sử dụng đến hết chu kỳ thanh toán hiện tại."]] },
  cta: { title: "Thiết kế tốt hơn bắt đầu từ một screenshot.", description: "Tạo audit đầu tiên miễn phí và biết chính xác điều gì cần cải thiện.", button: "Bắt đầu ngay" },
  footer: { privacy: "Quyền riêng tư", terms: "Điều khoản" }
};
const en: typeof vi = {
  nav: { features: "Features", how: "How it works", pricing: "Pricing", faq: "FAQ", login: "Sign in" },
  hero: { badge: "AI-powered UX audit", title: "Turn screenshots into clear UX decisions.", description: "Find usability and accessibility issues in seconds. Get specific recommendations to improve your design before shipping.", primary: "Audit for free", secondary: "See the product", note: "No credit card required · Results in seconds" },
  preview: { file: "Screenshot uploaded", issue: "CTA has low contrast", recommendation: "Increase the contrast ratio to improve readability." },
  proof: "Built for teams that ship products fast",
  features: { badge: "Features", title: "A UX reviewer that's always available.", description: "Go from screenshot to a prioritized improvement list ready for your backlog.", items: [["Structured audits","Score usability, accessibility, hierarchy, consistency, and UX writing."],["Context-aware AI","Analysis based on your product goals instead of generic design feedback."],["Clear priorities","Critical, major, and minor severity show your team what to fix first."],["Accessibility","Spot contrast, readability, target-size, and common accessibility barriers."],["Track progress","Save audit history by project and compare quality across iterations."],["Private by default","Screenshots live in a private bucket protected by Row Level Security."]] },
  how: { badge: "How it works", title: "From image to insight in 3 steps.", items: [["Upload a screenshot","Use a PNG, JPG, or WebP from any screen."],["AI analyzes it","The vision model evaluates five core UX dimensions."],["Get your report","Review scores, issues, and prioritized recommendations."]] },
  cases: { badge: "Use cases", title: "Useful at every design stage.", items: [["Designer","Get another perspective before design reviews and handoff."],["Product team","Evaluate flows quickly before adding them to a sprint."],["Agency","Standardize audit quality across client projects."],["Founder","Review your MVP without a full-time UX specialist."]] },
  comparison: { badge: "Before / After", title: "Less guessing. More evidence.", before: "Before UXLens", after: "After UXLens", beforeItems: ["Subjective, fragmented feedback","No clarity on the most important issue","Hours spent preparing design reviews","Accessibility problems are easily missed"], afterItems: ["Consistent scores across five dimensions","Issues ordered by impact","Specific, actionable recommendations","History that shows progress over time"] },
  pricing: { badge: "Pricing", title: "Start free, upgrade when you need to.", description: "Simple pricing with no hidden fees.", month: "/ month", popular: "Popular", freeCta: "Start for free", proCta: "Try Pro", free: ["3 audits per month","5 UX score dimensions","Prioritized issues","30-day history"], pro: ["Unlimited audits","Detailed AI analysis","Unlimited history","Report exports","Priority processing"] },
  faq: { badge: "FAQ", title: "Frequently asked questions.", items: [["Does UXLens replace a UX researcher?","No. UXLens quickly surfaces heuristic issues so your team can prepare for deeper research and design reviews."],["Are my screenshots secure?","Images are stored in a private Supabase Storage bucket protected by account-level Row Level Security."],["What does the AI evaluate?","Usability, accessibility, visual hierarchy, consistency, and UX writing."],["Can I cancel Pro at any time?","Yes. You can cancel and keep access until the end of your current billing period."]] },
  cta: { title: "Better design starts with one screenshot.", description: "Create your first audit for free and learn exactly what to improve.", button: "Get started" },
  footer: { privacy: "Privacy", terms: "Terms" }
};
export function getDictionary(locale: Locale) { return locale === "en" ? en : vi; }