"use client";
import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { BrainCircuit,Check,Eye,ListChecks,ScanSearch } from "lucide-react";
import { Button } from "@/components/ui/button";
import { capture } from "@/lib/analytics";
import { analysisResultSchema } from "@/lib/validations/analysis";
import { useAnalysisStore } from "@/store/use-analysis-store";
const steps=[{label:"Đang đọc cấu trúc giao diện",icon:Eye},{label:"Đánh giá 5 tiêu chí UX",icon:ScanSearch},{label:"Đối chiếu các screenshot",icon:BrainCircuit},{label:"Tạo đề xuất cải thiện",icon:ListChecks}];
export function ProcessingAudit(){const router=useRouter();const draft=useAnalysisStore();const[active,setActive]=useState(0);const[error,setError]=useState("");const started=useRef(false);
 useEffect(()=>{if(started.current)return;started.current=true;const progress=setInterval(()=>setActive(x=>Math.min(x+1,steps.length-1)),1000);const configured=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
  async function run(){if(!configured||!draft.screenshots.length){await new Promise(resolve=>setTimeout(resolve,4200));router.push("/dashboard/audits/demo");return}try{const body=new FormData();draft.screenshots.forEach(({file})=>body.append("images",file));body.append("context",draft.goal);body.append("productType",draft.productType);body.append("platform",draft.platform);body.append("screenType",draft.screenType);if(draft.projectId)body.append("projectId",draft.projectId);const response=await fetch("/api/analyze",{method:"POST",body});const payload=await response.json();if(!response.ok){if(payload.code==="QUOTA_EXCEEDED")capture("credit_exhausted");throw new Error(payload.error??"Không thể phân tích giao diện")}capture("audit_completed",{screenshots:draft.screenshots.length});if(payload.isFirstAudit)capture("first_audit");draft.setDraft({result:analysisResultSchema.parse(payload)});router.push(`/dashboard/audits/${payload.auditId}`)}catch(cause){setError(cause instanceof Error?cause.message:"Không thể phân tích giao diện")}finally{clearInterval(progress)}}void run();return()=>clearInterval(progress)},[draft,router]);
 if(error)return <div className="mx-auto grid min-h-[65vh] max-w-md place-items-center text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-full bg-destructive/10 text-destructive">!</span><h1 className="mt-5 text-2xl font-bold">Phân tích chưa hoàn tất</h1><p className="mt-2 text-sm text-muted-foreground">{error}</p><Button className="mt-6" onClick={()=>router.push("/dashboard/new")}>Quay lại New Audit</Button></div></div>;
 return <div className="mx-auto grid min-h-[70vh] max-w-xl place-items-center"><div className="w-full text-center"><div className="relative mx-auto size-24"><span className="absolute inset-0 animate-ping rounded-full bg-primary/10"/><span className="relative grid size-full place-items-center rounded-full border bg-card shadow-xl shadow-primary/10"><BrainCircuit className="size-10 animate-pulse text-primary"/></span></div><h1 className="mt-8 text-3xl font-bold">AI đang phân tích {draft.screenshots.length||1} screenshot</h1><p className="mt-2 text-muted-foreground">Các ảnh được xem như một flow thống nhất. Có thể mất 10–45 giây.</p><div className="mt-10 space-y-3 text-left">{steps.map(({label,icon:Icon},i)=><div key={label} className={`flex items-center gap-3 rounded-lg border p-3 transition ${i<=active?"border-primary/30 bg-primary/5":"opacity-40"}`}><span className={`grid size-8 place-items-center rounded-full ${i<active?"bg-primary text-primary-foreground":"bg-muted"}`}>{i<active?<Check className="size-4"/>:<Icon className={`size-4 ${i===active?"animate-pulse text-primary":""}`}/>}</span><span className="text-sm font-medium">{label}</span></div>)}</div><div className="mt-8 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all duration-700" style={{width:`${(active+1)/steps.length*100}%`}}/></div></div></div>}